### ISSUE TITLE
IndexOutOfRangeException when no command line argument is provided.

### ISSUE THREAD

**Issue by cosineblast** [jee-mj/bin-node-obj-cleaner#2]
At the very first line of the main function, it can be seen that when no command line argument is provided, the program crashes throwing
an unhandled IndexOutOfRangeException instead of handling it.

```cs
private static void Main(string[] args)
{
    string projectDirectory = DirectoryDetails(args[0]);
    // ...
}
```

**Comment by jee-mj** [comment]
> At the very first line of the main function, it can be seen that when no command line argument is provided, the program crashes throwing an unhandled IndexOutOfRangeException instead of handling it.
> 
> ```cs
> private static void Main(string[] args)
> {
>     string projectDirectory = DirectoryDetails(args[0]);
>     // ...
> }
> ```

If you are running it through an IDE, you'll want to replace the bit that says `args[0]`, with the directory you want to run it in, for example:

```cs
string projectDirectory = DirectoryDetails(@"/Users/figurantpp/Projects");
```
```cs
string projectDirectory = DirectoryDetails(@"C:\Users\figurantpp\source");
```

**Comment by jee-mj** [comment]
**OFFICIAL**

This is a low-priority issue, and thus will not be implemented in release for the moment as the issue is already mentioned in the README file in the packages. However, the code has been updated in the repository if you would like to build it yourself.

Alternative to updating the value of the `projectDirectory` string, you can add the code below and build it yourself:

```cs
if (args.Length == 0)
{
    Console.WriteLine("Please supply a directory to clean.\nThe program will now exit.");
    return;
}
```
